### ServiceProfile for servicea-svc.linkerd-demo ###
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: servicea-svc.linkerd-demo.svc.cluster.local
  namespace: linkerd-demo
spec:
  # A service profile defines a list of routes.  Linkerd can aggregate metrics
  # like request volume, latency, and success rate by route.
  routes:
  - name: 'GET /api/values (any)'

    # Each route must define a condition.  All requests that match the
    # condition will be counted as belonging to that route.  If a request
    # matches more than one route, the first match wins.
    condition:
      # The simplest condition is a path regular expression.
      pathRegex: '/api/values.*'

      # This is a condition that checks the request method.
      method: GET

    timeout: 5000ms
    isRetryable: true
    
    responseClasses:
    - condition:
        status:
          min: 500
          max: 599
      isFailure: true
  
  retryBudget:
    retryRatio: 0.2
    minRetriesPerSecond: 10
    ttl: 10s
