version: '3.4'

services:
  gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  servicea:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  serviceb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44352
    ports:
      - "57457:80"
      - "44352:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  bot:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

